let aws = require('aws-sdk')
let cache = false

/**
 * reads ws urls generated by cfn from ssm
 */
module.exports = function urls(callback) {

  let promise
  if (!callback) {
    promise = new Promise(function(res, rej) {
      callback = function(err, result) {
        err ? rej(err) : res(result)
      }
    })
  }

  if (cache) callback(null, cache)
  else {
    let ssm = new aws.SSM
    let Path = `/${process.env.ARC_CLOUDFORMATION}`
    ssm.getParametersByPath({Path, Recursive:true}, function done(err, result) {
      if (err) callback(err)
      else {
        let topic = param=> param.Name.split('/')[2] === 'ws'
        cache = result.Parameters.filter(topic).reduce((a, b)=> {
          a[b.Name.split('/')[3]] = b.Value
          return a
        }, {})
        callback(null, cache)
      }
    })
  }

  return promise
}
