let aws = require('aws-sdk')

/**
 * reads sqs topic arns generated by cfn from ssm
 */
module.exports = function lookupQueues(callback) {
  let ssm = new aws.SSM
  let Path = `/${process.env.ARC_CLOUDFORMATION}`
  ssm.getParametersByPath({Path, Recursive:true}, function done(err, result) {
    if (err) callback(err)
    else {
      let queue = param=> param.Name.split('/')[2] === 'queues'
      let queues = result.Parameters.filter(queue).reduce((a, b)=> {
        a[b.Name.split('/')[3]] = b.Value
        return a
      }, {})
      callback(null, queues)
    }
  })
}
