#!/bin/bash
# Checks if last commit message was semver
# - If so, deploy to production
# - And always deploy to staging
TAG=`git log -1 --pretty=%B`
if echo "$TAG" | grep '^\([0-9]\{1,\}\.\?\)\{3\}'; then
  npx arc deploy --production
fi
npx arc deploy --staging
