#!/bin/bash
# Checks if last commit message was semver-ish
# - If so, deploy to production
# - And always deploy to staging
TAG=`git log -1 --pretty=%B`
if echo "$TAG" | grep -E '^([0-9]+\.){0,2}(\*|[0-9]+)$'; then
  npx arc deploy --production
fi
npx arc deploy --staging
